LAB_10/LAB_06/Controllers/AdminController.cs
using LAB_06.Infastructure;
using LAB_06.Models;
using LAB_06.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LAB_06.Controllers
{
    public class AdminController : Controller
    {
        private ISharedRepository repository;

        public AdminController(ISharedRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index() => View(repository.Players);

        public ViewResult Edit(int playerId) =>
            View(repository.Players
                .FirstOrDefault(p => p.PlayerId == playerId));

        [HttpPost]
        public IActionResult Edit(Player player)
        {
            if (ModelState.IsValid)
            {
                repository.SavePlayer(player);
                TempData["message"] = $"{player.FirstName} has been saved";
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(player);
            }
        }

        public ViewResult Create() => View("Edit", new Player());

        [HttpPost]
        public IActionResult Delete(int playerId)
        {
            Player deletedPlayer = repository.DeletePlayer(playerId);
            if (deletedPlayer != null)
            {
                TempData["message"] = $"{deletedPlayer.FirstName} was deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

LAB_10/LAB_06/Controllers/CartController.cs
using LAB_06.Infastructure;
using LAB_06.Models;
using LAB_06.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LAB_06.Controllers
{
    public class CartController : Controller
    {
        private ISharedRepository repository;
        private Cart cart;

        public CartController(ISharedRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int playerId, string returnUrl)
        {
            Player player = repository.Players
                .FirstOrDefault(p => p.PlayerId == playerId);

            Console.WriteLine(playerId);
            if (player != null)
            {
                cart.AddItem(player, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int playerId,
                string returnUrl)
        {
            Player player = repository.Players
                .FirstOrDefault(p => p.PlayerId == playerId);

            if (player != null)
            {
                cart.RemoveLine(player);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

LAB_10/LAB_06/Controllers/PlayerController.cs
using LAB_06.Models;
using LAB_06.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LAB_06.Controllers
{
    public class PlayerController : Controller
    {
        private ISharedRepository playRepo;
        public int PageSize = 5;

        public PlayerController(ISharedRepository playRepo)
        {
            this.playRepo = playRepo;
        }


        public ViewResult Simple(string teamName, int page = 1)
        {
            return View(new PlayersListViewModel
            {
                Players = playRepo.Players
                .Where(p => teamName == null || p.Team == null || p.Team.Name == teamName)
                .OrderBy(p => p.PlayerId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = teamName == null ?
                        playRepo.Players.Count() :
                        playRepo.Players.Where(e =>
                            e.FirstName == teamName).Count()
                },
                CurrentTeamName = teamName
            });

        }

        public ViewResult PlayerChart()
        {
            ViewBag.Players = Newtonsoft.Json.JsonConvert.SerializeObject(playRepo.Players);
            ViewBag.Positions = Newtonsoft.Json.JsonConvert.SerializeObject(playRepo.Positions);
            return View();
        }


        public ViewResult RealPlayers(string teamName)
        {
            Console.WriteLine(teamName);

            ViewBag.teamName = teamName;
            ViewBag.Teams = Newtonsoft.Json.JsonConvert.SerializeObject(playRepo.Teams);
            return View(playRepo.Teams);
        }
    }
}

LAB_10/LAB_06/Controllers/TeamController.cs
using LAB_06.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LAB_06.Controllers
{
    public class TeamController : Controller
    {
        private ISharedRepository sharedRepo;

        public TeamController(ISharedRepository sharedRepo)
        {
            this.sharedRepo = sharedRepo;
        }

        public ViewResult Simple()
        {
            return View(sharedRepo.Teams);
        }

        public ViewResult Complex()
        {
            return View(sharedRepo.Teams);
        }
    }
}

LAB_10/LAB_06/Views/Shared/PlayerInfoPartial.cshtml
@model Player

<tr>
    <td>@Model.PlayerId</td>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>@Model.Team.Name</td>
    <td>@Model.Position.Name</td>
    <td>
        <form id="@Model.PlayerId" asp-action="AddToCart"
              asp-controller="Cart" method="post">
            <input type="hidden" asp-for="PlayerId" />
            <input type="hidden" name="returnUrl"
                   value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                @string.Format("{0:c}", @Model.Position.Salary)
                <button type="submit"
                        class="btn btn-success btn-sm pull-right" style="float:right">
                    Add To Cart
                </button>
        </form>
    </td>
</tr>

LAB_10/LAB_06/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

</head>
<body class="m-1 p-1">
    <div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>
    @if (TempData["message"] != null) {
    <div class="alert alert-success mt-1">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

LAB_10/LAB_06/Views/Shared/_SharedLayout.cshtml
<html>
<head>

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>

        body {
            border: 5px solid black;
            border-radius: 10px;
            padding: 15px;
            margin: 0 auto;
            border: 2px solid black;
            border-radius: 10px;
            height: fit-content;
            width: 1500px;
        }

        .addCD {
            margin: 20 0px;
            color: white !important;
        }

        .nav-btn-text {
            color: white !important;
        }

        .teamNames {
            display: flex;
            flex-direction: column;
            justify-content: space-evenly;
            align-items: flex-start;
        }
    </style>
</head>

<title>@ViewBag.Title - FINAL</title>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="btn btn-dark"><a asp-controller="Player" asp-action="Simple" class="nav-btn-text">Player - Simple</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Position" asp-action="Simple" class="nav-btn-text">Position - Simple</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Stadium" asp-action="Simple" class="nav-btn-text">Stadium - Simple</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Team" asp-action="Simple" class="nav-btn-text">Team - Simple</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Team" asp-action="Complex" class="nav-btn-text">Team - Complex</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Admin" asp-action="Index" class="nav-btn-text">Admin</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="TeamAdmin" asp-action="Index" class="nav-btn-text">TeamAdmin</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Player" asp-action="PlayerChart" class="nav-btn-text">PlayerChart</a></button>
                <button type="button" class="btn btn-dark"><a asp-controller="Player" asp-action="RealPlayers" class="nav-btn-text">RealPlayers</a></button>


                <div class="col-2 text-right">
                    @await Component.InvokeAsync("CartSummary")
                </div>
            </div>


        </div>
    </nav>


    <div class="row m-1 p-1">
        <div id="teamNames" class="teamNames col-3">
            @await Component.InvokeAsync("TeamMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>


</body>
</html>